version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mailtrain
      - MYSQL_DATABASE=mailtrain
      - MYSQL_USER=mailtrain
      - MYSQL_PASSWORD=mailtrain
    volumes:
      - mailtrain-mysq-data:/var/lib/mysql
  redis:
    image: redis:3.0
    volumes:
      - mailtrain-redis-data:/data
  mailtrain:
    image: mailtrain:1.24
    depends_on:
      - mysql
      - redis
    volumes:
      - mailtrain-node-config:/app/config
      - mailtrain-node-data:/app/public/grapejs/uploads
      - mailtrain-node-data:/app/public/mosaico/uploads
volumes:
  mailtrain-mysq-data: {}
  mailtrain-redis-data: {}
  mailtrain-node-data: {}
  mailtrain-node-config: {}
