# Process title visible in monitoring logs and process listing
title: mailtrain

log:
  # silly|verbose|info|http|warn|error|silent
  level: info

# Default language to use
defaultLanguage: en-US

# Enabled languages
enabledLanguages:
- en-US
- es-ES
- de-DE
- fk-FK

mysql:
  host: localhost
  user: mailtrain
  password: mailtrain
  database: mailtrain
  # Some installations, eg. MAMP can use a different port (8889)
  # MAMP users should also turn on Allow network access to MySQL otherwise MySQL might not be accessible
  port: 3306
  charset: utf8mb4
  # The timezone configured on the MySQL server. This can be 'local', 'Z', or an offset in the form +HH:MM or -HH:MM
  # If the MySQL server runs on the same server as Mailtrain, use 'local'
  timezone: local
